### ISSUE TITLE
"Polytone" Mod Conflict: Changing Fullscreen Resolution Crashes Game

### ISSUE THREAD

**Issue by Firebolt360** [Bestsoft101/Better-Fullscreen#1]
Issue stated in title.

All mods are up to date (Borderless Fullscreen, Fabric API, Mod Menu, and Polytone). Tested in 1.21.1.

**Comment by Bestsoft101** [comment]
Fixed
https://modrinth.com/mod/borderless-fullscreen/version/2.0.1
