### ISSUE TITLE
Using a screenshot tool causes the game to show the ESC/pause menu

### ISSUE THREAD

**Issue by NorthernLawOfficial** [Bestsoft101/Better-Fullscreen#3]
As the title says, using an application such as Lightshot or Flameshot causes the game to show the ESC menu. These are programs made to screenshot an area of your choosing on your screen(s). This very well might be a limitation of the fact that Minecraft does not have natural borderless fullscreen but I wasn't sure so figured I'd make it known here.

When trying to screenshot it will either bring up the ESC menu or your inventory depending on where you last were, most of the time it just does the ESC menu though I've noticed.

Essentially this makes taking screenshots in Minecraft still impossible the right way because while in normal fullscreen it doesn't work since the window closes, with this mod you get closer since the game stays open but the pause menu does appear. So even with this mod, to take a proper screenshot you still have to F11 to go into windowed mode and then fullscreen it and take a screenshot then.

Again this might just be a limitation in Minecraft but figured it'd be worth an ask since I truly do not know the answer. Thank you.

**Comment by Bestsoft101** [comment]
The game goes into the pause menu because using the screenshot tool unfocuses the game, this has nothing to do with the mod. You can disable this by pressing F3 + P. Also, you can just press F2 to take a screenshot, there is no need for a screenshot tool.

**Comment by NorthernLawOfficial** [comment]
Yeah figured it was a limitation of the game just wanted to be sure though because I never had the chance to even screenshot in fullscreen because of how the game works so this was my first time trying it with this mod, thought maybe it would kill 2 birds 1 stone.

Yes I am well aware of the F2 screenshot method which I think I press by accident 99.8% of the time and I am not sure why I haven't disabled it yet, thanks for reminding me to empty my folder of all those useless screenshots actually. The reason I use a screenshot tool is I take it with purpose every time and sometimes want a specific area of the screen to be screenshot along with ease of copying it and then it's just deleted, no need to have it in a folder. As well as drawing on the screenshot or inserting shapes to show what I am screenshotting for specific things. Flameshot is great it's open source and I use it for literally everything.

Thank you for your help though I figured it wasn't something this mod could do after testing but wanted to make sure.
