### ISSUE TITLE
Disabled the mod with 'Mod Menu' mod, cant access properties now

### ISSUE THREAD

**Issue by William8million** [Bestsoft101/Better-Fullscreen#4]
i cant turn the mod back on. when i click properties, the game crashes.

it says:
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "b100.gui.config.CustomOptionElement.setValue(Object)" because "this.fullscreenResolutionButton" is null

help!
![image_2024-10-24_164510241](https://github.com/user-attachments/assets/d03461df-5511-4996-8a52-be0430709de8)

**Comment by William8million** [comment]
FOUND A FIX!
![image_2024-10-24_164835459](https://github.com/user-attachments/assets/81fd5c63-7b3d-4d20-b8bb-17f3bb85bf7d)
go to the config file in the .minecraft folder, go to fixfullscreen file or whatever, and turn on enable mods!

**Comment by William8million** [comment]
![image_2024-10-24_164958964](https://github.com/user-attachments/assets/6f40c4b8-25dc-4a30-84bb-cbebc4788cb1)

**Comment by Bestsoft101** [comment]
Fixed in 2.1.0
