### ISSUE TITLE
Doesn't work in 1.21.4 (normal fullscreen behaviour)

### ISSUE THREAD

**Issue by Delivator** [Bestsoft101/Better-Fullscreen#5]
Seems to be broken with the latest version. Game start and I can change the mod settings but screen goes blank when when alt-tabbing.

I also noticed that setting the OpenGL present method in the nvidia controlpanel also doesnt seem to work with this version of minecraft: https://www.reddit.com/r/nvidia/comments/yf6hiw/psa_you_can_now_elevate_openglvulkan_games_to_a/

**Comment by Bestsoft101** [comment]
It works fine for me. If you enable it through the video settings menu, make sure to set it to Borderless instead of On, or enable Borderless Fullscreen in the mod options

I dont know what the present method option does or what to do with that information

**Comment by Delivator** [comment]
Okay the setting I was looking for is the "Windows Fullscreen Optimization" with it disabeled I can alt-tab without my screen going blank. The other issue is something else that I though was related.
